version: '3.8'

services:
  wallpaper-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
          - ./wallpapers:/app/backend/wallpapers
    environment:
          - PYTHONPATH=/app
          - FLASK_ENV=production
          - FLASK_APP=backend/app.py
          - FLASK_RUN_HOST=0.0.0.0
          - FLASK_RUN_PORT=5000
    restart: unless-stopped
    container_name: wallpaper-app