version: '3.8'

services:
  wallpaper-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend/wallpapers:/app/backend/wallpapers
      - ./backend/thumbnails:/app/backend/thumbnails
      - ./backend/wallpaper_cache.json:/app/backend/wallpaper_cache.json
    environment:
          - PYTHONPATH=/app
          - FLASK_ENV=production
          - FLASK_APP=backend/app.py
          - FLASK_RUN_HOST=0.0.0.0
          - FLASK_RUN_PORT=5000
    restart: unless-stopped
    container_name: wallpaper-app